### ISSUE TITLE
Copy Java pom.xml to outdir

### ISSUE THREAD

**Issue by jsteinich** [cdklabs/jsii-srcmak#366]
jsii-pacmak generates a pom.xml file alongside the generated java code `src` directory; however, jsii-srcmak only copies the `src` directory. That works out fine when putting the generated code side of application code (what cdk8s and cdktf do currently). That `pom.xml` would be needed (or another one) in order to place the generated code elsewhere and reference as a separate project. That would also align better with what the other supported languages are doing.
Could make it an option to prevent breaking existing uses.

**Comment by eladb** [comment]
In this case, why not use jsii-pacmak directly?

**Comment by jsteinich** [comment]
> In this case, why not use jsii-pacmak directly?

cdktf started off that way, but when fixing Windows issues and adding languages we switched to jsii-srcmak since it already took care of those things.
Going back to direct use would just be copying code and changing a line or two, so definitely could go that route.

Is there some reason why the Java support works differently than other languages?
